spring.application.name=web-service\

server.port=8080

spring.thymeleaf.cache=false

neurosocial.db.address=jdbc:postgresql://localhost:5432/social
neurosocial.db.user=social_admin
neurosocial.db.password=admin
