CREATE TABLE public.personalities (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	prompt varchar NOT NULL,
	CONSTRAINT personalities_pk PRIMARY KEY (id),
	CONSTRAINT personalities_unique UNIQUE (prompt)
);